### ISSUE TITLE
[FEATURE] terraform lock & sensitive vars

### ISSUE THREAD

**Issue by elreydetoda** [elreydetoda/packer-kali_linux#90]
**To-Do**
- [ ] add locks to all terraform directories
   - [ ] have process for upgrading lock files
- [ ] mark packet project as sensitive 

**Vendor (Optional)**
HashiCorp

**link**
https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-general-availability

**Additional context**
With the release of terraform 0.14, they introduced locking so you can have a more reproducible run for applying terraform infra. Also, they now allow you to mark variables as sensitive, and I have always wanted to do that for the packet project ID.
